apps:
  deployment:
    imagePullPolicy: Always
config:
  backend:
    default_image: r-ubuntu-resolute
    allowed_images:
      - julia-alpine-3-24
      - julia-ubuntu-resolute
      - python-ubuntu-resolute
      - r-alpine-3-24
      - r-ubuntu-resolute
execEnv:
  config: |
    [image.julia-alpine-3-24]
    image = "reg.ricochet.rs/exec-envs/julia-alpine:2026-08-3.24"
    os = "alpine-3.24"
    description = "Latest julia preview environment from release 2026-08"
    arch = ["linux/amd64"]
    julia = [
      { version = "1.10.10", bin = "/usr/local/bin/julia1.10" },
      { version = "1.12.0-rc1", bin = "/usr/local/bin/julia1.12" },
    ]
    quarto = [{ version = "1.10.18", bin = "/opt/quarto/bin/quarto" }]

    [image.julia-ubuntu-resolute]
    image = "reg.ricochet.rs/exec-envs/julia-ubuntu:2026-08-resolute"
    os = "ubuntu-26.04"
    description = "Latest julia preview environment from release 2026-08"
    arch = ["linux/amd64", "linux/arm64"]
    julia = [
      { version = "1.10.12", bin = "/usr/local/bin/julia1.10" },
      { version = "1.12.7", bin = "/usr/local/bin/julia1.12" },
    ]
    quarto = [{ version = "1.10.18", bin = "/opt/quarto/bin/quarto" }]

    [image.python-ubuntu-resolute]
    image = "reg.ricochet.rs/exec-envs/python-ubuntu:2026-08-resolute"
    os = "ubuntu-26.04"
    description = "Latest python preview environment from release 2026-08"
    arch = ["linux/amd64", "linux/arm64"]
    python = [
      { version = "3.12.13", bin = "/usr/local/bin/python3.12" },
      { version = "3.13.14", bin = "/usr/local/bin/python3.13" },
      { version = "3.14.6", bin = "/usr/local/bin/python3.14" },
    ]
    quarto = [{ version = "1.10.18", bin = "/opt/quarto/bin/quarto" }]

    [image.r-alpine-3-24]
    image = "reg.ricochet.rs/exec-envs/r-alpine:2026-08-3.24"
    os = "alpine-3.24"
    description = "Latest r preview environment from release 2026-08"
    arch = ["linux/amd64", "linux/arm64"]
    r = [
      { version = "4.4.3", bin = "/opt/R/4.4.3/bin/R" },
      { version = "4.5.3", bin = "/opt/R/4.5.3/bin/R" },
      { version = "4.6.1", bin = "/opt/R/4.6.1/bin/R" },
    ]
    quarto = [{ version = "1.10.18", bin = "/opt/quarto/bin/quarto" }]

    [image.r-ubuntu-resolute]
    image = "reg.ricochet.rs/exec-envs/r-ubuntu:2026-08-resolute"
    os = "ubuntu-26.04"
    description = "Latest r preview environment from release 2026-08"
    arch = ["linux/amd64", "linux/arm64"]
    r = [
      { version = "4.4.3", bin = "/opt/R/4.4.3/bin/R" },
      { version = "4.5.3", bin = "/opt/R/4.5.3/bin/R" },
      { version = "4.6.1", bin = "/opt/R/4.6.1/bin/R" },
    ]
    quarto = [{ version = "1.10.18", bin = "/opt/quarto/bin/quarto" }]
