#!/usr/bin/env bash

set -euo pipefail

repository_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
mode=${1:-update}
if [[ ${mode} != update && ${mode} != --check ]]; then
  echo "Usage: $0 [--check]" >&2
  exit 1
fi
temporary=$(mktemp -d)
trap 'rm -rf "${temporary}"' EXIT

for architecture in amd64 arm64; do
  output="${temporary}/r-sysreqs-build-${architecture}.yaml"
  cat >"${output}" <<EOF
# Generated by scripts/render-r-sysreqs-workflows.sh from r/sysreqs/config.json.
when:
  event: pull_request
  path:
    include:
      - 'r/**'
      - 'scripts/*r-sysreqs*'
      - '.crow/r-sysreqs-build-*.yaml'

depends_on:
  - lint

labels:
  backend: docker
  platform: linux/${architecture}

matrix:
  include:
EOF
  jq -r --arg quote "'" '.platforms[] | . as $platform |
    "    - target: " + $quote + .id + $quote + "\n" +
    "      containerfile: " + $quote + "r/" + .family + "/Containerfile" + $quote + "\n" +
    "      OS_VERSION: " + $quote + (.id | ltrimstr($platform.family + "-")) + $quote' \
    "${repository_root}/r/sysreqs/config.json" >>"${output}"
  cat >>"${output}" <<EOF

steps:
  build-image:
    image: codefloe.com/crow-plugins/docker-buildx:2.5.1
    settings:
      mtu: 1350
      platforms: linux/${architecture}
      repo: ricochetrs/r-sysreqs-validation
      tags: \${target}-${architecture}
      dockerfile: \${containerfile}
      dry_run: true
      build_args_from_env:
        - OS_VERSION
EOF
  destination="${repository_root}/.crow/r-sysreqs-build-${architecture}.yaml"
  if [[ ${mode} == --check ]]; then
    diff -u "${destination}" "${output}"
  else
    cp "${output}" "${destination}"
  fi
done
