#!/usr/bin/env bash

set -euo pipefail

repository_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
readme_path="${repository_root}/README.md"
generated_section=$(mktemp)
rendered_readme=$(mktemp)

if ! grep -Fxq '<!-- releases:start -->' "${readme_path}" || ! grep -Fxq '<!-- releases:end -->' "${readme_path}"; then
    echo "README.md is missing the release index markers" >&2
    exit 1
fi

{
    echo '<!-- This section is generated by scripts/render-release-index.sh. -->'
    echo
    echo '| Release | Retained through | Environments | CI |'
    echo '| --- | --- | --- | --- |'

    while IFS= read -r release_metadata; do
        release_month=$(jq -r '.release' "${release_metadata}")
        retention_until=$(jq -r '.retentionUntil' "${release_metadata}")
        environment_count=$(jq '.environments | length' "${release_metadata}")
        ci_status=$(jq -r '.ci.status // empty' "${release_metadata}")
        ci_url=$(jq -r '.ci.url // empty' "${release_metadata}")
        ci="Not recorded"
        if [[ ${ci_status} == passed && -n ${ci_url} ]]; then
            ci="[Passed](${ci_url})"
        fi

        printf '| [%s](releases/%s/) | %s | %s | %s |\n' \
            "${release_month}" "${release_month}" "${retention_until}" "${environment_count}" "${ci}"
    done < <(find "${repository_root}/releases" -mindepth 2 -maxdepth 2 -name release.json -print | sort -r)
} >"${generated_section}"

sed -n '1,/^<!-- releases:start -->$/p' "${readme_path}" >"${rendered_readme}"
cat "${generated_section}" >>"${rendered_readme}"
sed -n '/^<!-- releases:end -->$/,$p' "${readme_path}" >>"${rendered_readme}"
mv "${rendered_readme}" "${readme_path}"
