#!/usr/bin/env bash

set -euo pipefail

repository_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
readme_path="${repository_root}/README.md"
generated_section=$(mktemp)
rendered_readme=$(mktemp)

if ! grep -Fxq '<!-- releases:start -->' "${readme_path}" || ! grep -Fxq '<!-- releases:end -->' "${readme_path}"; then
    echo "README.md is missing the release index markers" >&2
    exit 1
fi

{
    echo '<!-- This section is generated by scripts/render-release-index.sh. -->'

    while IFS= read -r release_metadata; do
        release_month=$(jq -r '.release' "${release_metadata}")
        retention_until=$(jq -r '.retentionUntil' "${release_metadata}")

        printf '\n### [%s](releases/%s/)\n\n' "${release_month}" "${release_month}"
        printf 'Retained through at least %s.\n\n' "${retention_until}"
        echo '| Environment | Contents | Platforms | Definition | Images |'
        echo '| --- | --- | --- | --- | --- |'

        jq -c '.environments[]' "${release_metadata}" | while IFS= read -r environment; do
            id=$(jq -r '.id' <<<"${environment}")
            image=$(jq -r '.image' <<<"${environment}")
            release_tag=$(jq -r '.releaseTag' <<<"${environment}")
            platforms=$(jq -r '.platforms | join(", ")' <<<"${environment}")
            r_version=$(jq -r '.versions.r' <<<"${environment}")
            python_versions=$(jq -r '.versions.python | join(", ")' <<<"${environment}")
            julia_version=$(jq -r '.versions.julia' <<<"${environment}")
            quarto_version=$(jq -r '.versions.quarto' <<<"${environment}")
            contents="R ${r_version}; Python ${python_versions}; Julia ${julia_version}; Quarto ${quarto_version}"
            definition="releases/${release_month}/${id}/Containerfile"
            docker_hub_url="https://hub.docker.com/r/ricochetrs/${image}/tags?name=${release_tag}"
            registry_url="https://reg.ricochet.rs/v2/exec-envs/${image}/manifests/${release_tag}"

            # shellcheck disable=SC2016
            printf '| `%s` | %s | %s | [Containerfile](%s) | [Docker Hub](%s), [Ricochet Registry](%s) |\n' \
                "${id}" "${contents}" "${platforms}" "${definition}" "${docker_hub_url}" "${registry_url}"
        done
    done < <(find "${repository_root}/releases" -mindepth 2 -maxdepth 2 -name release.json -print | sort -r)
} >"${generated_section}"

sed -n '1,/^<!-- releases:start -->$/p' "${readme_path}" >"${rendered_readme}"
cat "${generated_section}" >>"${rendered_readme}"
sed -n '/^<!-- releases:end -->$/,$p' "${readme_path}" >>"${rendered_readme}"
mv "${rendered_readme}" "${readme_path}"
