#!/usr/bin/env bash

set -euo pipefail

repository_root=${RELEASE_REPOSITORY_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)}
output_directory=${1:-${repository_root}/.crow}
plugin_image=${RELEASE_BUILDX_PLUGIN:-codefloe.com/crow-plugins/docker-buildx:2.5.0}
release_registry=${RELEASE_SOURCE_REGISTRY:-reg.ricochet.rs/exec-envs}
docker_hub_namespace=${RELEASE_DOCKER_HUB_NAMESPACE:-docker.io/ricochetrs}

for command in jq yq; do
    if ! command -v "${command}" >/dev/null; then
        echo "Required command is unavailable: ${command}" >&2
        exit 1
    fi
done

mkdir -p "${output_directory}"

banner() {
    printf '# Generated by scripts/render-release-workflows.sh from release/environments.\n'
    # shellcheck disable=SC2016  # the backticks are Markdown, not a command substitution
    printf '# Run `just render-release-workflows` after changing a build matrix; check-releases.sh fails on drift.\n'
}

month_variable() {
    printf 'variables:\n'
    printf '  RELEASE_MONTH:\n'
    printf '    description: Calendar month as YYYY-MM. Crow cron cannot pass a variable or expose a date, so every release states it.\n'
    printf '    required: true\n'
    printf '  RELEASE_REBUILD:\n'
    printf '    description: Set to true to replace existing calendar tags during an archived release rebuild.\n'
    printf '    options:\n'
    printf "      - 'false'\n"
    printf "      - 'true'\n"
    printf "    default: 'false'\n"
    printf '  RELEASE_METADATA_ONLY:\n'
    printf '    description: Set to true to archive images that are already published without building or promoting them.\n'
    printf '    options:\n'
    printf "      - 'false'\n"
    printf "      - 'true'\n"
    printf "    default: 'false'\n"
}

ricochet_login() {
    printf '        - registry: https://reg.ricochet.rs\n'
    # shellcheck disable=SC2016  # the dollar belongs to the robot account name
    printf "          username: 'robot\$ricochet'\n"
    printf '          password:\n'
    printf '            from_secret: ricochet_registry_token\n'
}

docker_hub_login() {
    printf '        - registry: https://index.docker.io/v1/\n'
    printf '          username: ricochetbot\n'
    printf '          password:\n'
    printf '            from_secret: ricochet_dockerhub_token\n'
}

# Every entry carries its lifecycle window because a matrix cannot be filtered at run
# time. Only a build reads the Containerfile path and the build arguments, so merge
# and publish entries stop at the identity and window they address an image by.
emit_matrix() {
    local platform_filter=${1:-}
    local platform_set=${2:-}
    local build_inputs=${3:-}
    local definition
    local platforms
    local matrix_program

    # shellcheck disable=SC2016  # the dollar names are jq bindings, not shell variables
    matrix_program='
            .image as $image
            | .containerfile as $containerfile
            | .environments[]
            | (if has("release_suffix") then .release_suffix else (.JULIA_VERSION + "-" + (.OS_VERSION | tostring)) end) as $suffix
            | "    - name: \($q)\($image)\($q)",
              "      release_suffix: \($q)\($suffix)\($q)",
              "      release_from: \($q)\(.release_from // "0000-01")\($q)",
              "      release_through: \($q)\(.release_through // "9999-12")\($q)"'
    # Every build entry states all three arguments so none is ever unset. An argument
    # its own Containerfile does not declare is unused by that build.
    if [[ -n ${build_inputs} ]]; then
        # shellcheck disable=SC2016  # the dollar names are jq bindings, not shell variables
        matrix_program+=',
              "      containerfile: \($q)\($containerfile)\($q)",
              "      R_VERSION: \($q)\(.R_VERSION // "unused")\($q)",
              "      JULIA_VERSION: \($q)\(.JULIA_VERSION // "unused")\($q)",
              "      OS_VERSION: \($q)\(.OS_VERSION)\($q)"'
    fi

    printf 'matrix:\n  include:\n'
    for definition in "${repository_root}"/release/environments/*.yaml; do
        platforms=$(yq -r '.platforms' "${definition}")
        if [[ -n ${platform_filter} ]]; then
            [[ ",${platforms}," == *",${platform_filter},"* ]] || continue
        fi
        if [[ -n ${platform_set} ]]; then
            [[ ${platforms} == "${platform_set}" ]] || continue
        fi

        yq -o=json '.' "${definition}" | jq -r --arg q "'" "${matrix_program}"
    done
}

lifecycle_guard() {
    printf '    when:\n'
    printf "      evaluate: 'RELEASE_MONTH >= release_from && RELEASE_MONTH <= release_through'\n"
}

for platform in linux/amd64 linux/arm64; do
    architecture=${platform#linux/}
    {
        banner
        cat <<YAML
when:
  event:
    - manual
  branch:
    - main
  evaluate: "RELEASE_METADATA_ONLY != 'true'"

depends_on:
  - lint

# backend keeps this off a local-backend agent, which execs the image field as a
# command. platform keeps an arm64 build off an amd64 agent, where it would fall back
# to emulation these images cannot survive.
labels:
  backend: docker
  platform: ${platform}

YAML
        month_variable
        printf '\n'
        emit_matrix "${platform}" "" build-inputs
        cat <<YAML

steps:
  build-image:
YAML
        lifecycle_guard
        cat <<YAML
    image: ${plugin_image}
    settings:
      mtu: 1350
      platforms: ${platform}
      repo: ${release_registry}/\${name}
      tags: \${RELEASE_MONTH}-\${release_suffix}-${architecture}
      dockerfile: \${containerfile}
      provenance: true
      sbom: true
      build_args_from_env:
        - R_VERSION
        - JULIA_VERSION
        - OS_VERSION
      logins:
YAML
        ricochet_login
    } >"${output_directory}/build-${architecture}.yaml"
done

# One merge workflow per distinct platform set: an environment published for amd64
# only must not list an arm64 source that was never built.
while IFS= read -r platforms; do
    slug=$(printf '%s' "${platforms}" | sed 's|linux/||g; s|,|-|g')
    {
        banner
        cat <<YAML
when:
  event:
    - manual
  branch:
    - main
  evaluate: "RELEASE_METADATA_ONLY != 'true'"

depends_on:
YAML
        while IFS= read -r platform; do
            printf '  - build-%s\n' "${platform#linux/}"
        done < <(tr ',' '\n' <<<"${platforms}")
        cat <<YAML

# Composing an index reads registry metadata only, so it needs no builder.
labels:
  backend: docker

YAML
        month_variable
        printf '\n'
        emit_matrix "" "${platforms}"
        cat <<YAML

steps:
  merge-manifest:
YAML
        lifecycle_guard
        cat <<YAML
    image: ${plugin_image}
    settings:
      manifest: true
      repo: ${release_registry}/\${name}
      tags: \${RELEASE_MONTH}-\${release_suffix}
      manifest_sources:
YAML
        while IFS= read -r platform; do
            # shellcheck disable=SC2016  # ${...} is Crow substitution, resolved at run time
            printf '        - %s/${name}:${RELEASE_MONTH}-${release_suffix}-%s\n' \
                "${release_registry}" "${platform#linux/}"
        done < <(tr ',' '\n' <<<"${platforms}")
        printf '      logins:\n'
        ricochet_login
    } >"${output_directory}/merge-${slug}.yaml"
done < <(for definition in "${repository_root}"/release/environments/*.yaml; do
    yq -r '.platforms' "${definition}"
done | sort -u)

# Docker Hub is published by the plugin, while the release workflows use the same
# filtered credential only to verify the published manifests.
{
    banner
    cat <<YAML
when:
  event:
    - manual
  branch:
    - main
  evaluate: "RELEASE_METADATA_ONLY != 'true'"

depends_on:
YAML
    for merge_workflow in "${output_directory}"/merge-*.yaml; do
        printf '  - %s\n' "$(basename "${merge_workflow}" .yaml)"
    done
    cat <<YAML

labels:
  backend: docker

YAML
    month_variable
    printf '\n'
    emit_matrix
    cat <<YAML

steps:
  publish-manifest:
YAML
    lifecycle_guard
    cat <<YAML
    image: ${plugin_image}
    settings:
      manifest: true
      repo: ${docker_hub_namespace}/\${name}
      tags: \${RELEASE_MONTH}-\${release_suffix}
      manifest_sources:
        - ${release_registry}/\${name}:\${RELEASE_MONTH}-\${release_suffix}
      logins:
YAML
    ricochet_login
    docker_hub_login
} >"${output_directory}/publish.yaml"

echo "Rendered release workflows into ${output_directory}"
