#!/usr/bin/env bash
# Render the Ricochet catalogue for a monthly release, mirror the latest one at the repository root,
# and refresh releases/index.json, which Ricochet reads to offer every archived month.

set -euo pipefail

repository_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
release_month=${1:-}
output=${2:-}

# shellcheck source=scripts/lib/environment-toml.sh
source "${repository_root}/scripts/lib/environment-toml.sh"

if ! command -v jq >/dev/null; then
    echo "Required command is unavailable: jq" >&2
    exit 1
fi

latest_metadata=$(find "${repository_root}/releases" -mindepth 2 -maxdepth 2 -name release.json -print | sort -r | head -n 1)
if [[ -z ${release_month} ]]; then
    release_metadata=${latest_metadata}
else
    release_metadata="${repository_root}/releases/${release_month}/release.json"
fi

if [[ -z ${release_metadata:-} || ! -f ${release_metadata} ]]; then
    echo "Release metadata does not exist: ${release_metadata:-none}" >&2
    exit 1
fi

release=$(jq -r '.release' "${release_metadata}")
rendered=$(mktemp)
remove_working_files() {
    rm -f "${rendered}"
}
trap remove_working_files EXIT

{
    echo "# Ricochet execution environments published by ricochet-rs/exec-envs for release ${release}."
    echo "# Generated by scripts/render-catalogue.sh; edit the release metadata instead of this file."
    while IFS= read -r environment; do
        echo
        render_environment_toml "${environment}" dockerHub "ricochet-rs/exec-envs $(jq -r '.id' <<<"${environment}") from release ${release}" "${release}"
    done < <(jq -c '.environments | sort_by(.id) | .[]' "${release_metadata}")
} >"${rendered}"

if [[ -n ${output} ]]; then
    mkdir -p "$(dirname "${output}")"
    mv "${rendered}" "${output}"
    exit 0
fi

cp "${rendered}" "$(dirname "${release_metadata}")/catalogue.toml"
if [[ ${release_metadata} == "${latest_metadata}" ]]; then
    cp "${rendered}" "${repository_root}/catalogue.toml"
fi
"${repository_root}/scripts/render-release-index-json.sh"
