#!/usr/bin/env bash

set -euo pipefail

repository_root=${RELEASE_REPOSITORY_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)}
output_directory=${1:-${repository_root}/.crow}
plugin_image=${RELEASE_BUILDX_PLUGIN:-codefloe.com/crow-plugins/docker-buildx:2.5.0}
release_registry=${RELEASE_SOURCE_REGISTRY:-reg.ricochet.rs/exec-envs}

for command in jq yq; do
    if ! command -v "${command}" >/dev/null; then
        echo "Required command is unavailable: ${command}" >&2
        exit 1
    fi
done

mkdir -p "${output_directory}"

generated_banner() {
    printf '# Generated by scripts/render-release-workflows.sh from release/environments.\n'
    # shellcheck disable=SC2016  # the backticks are Markdown, not a command substitution
    printf '# Run `just render-release-workflows` after changing a build matrix; check-releases.sh fails on drift.\n'
}

registry_login() {
    printf '      logins:\n'
    printf '        - registry: https://reg.ricochet.rs\n'
    printf "          username: 'robot\$ricochet'\n"
    printf '          password:\n'
    printf '            from_secret: ricochet_registry_token\n'
}

# Each entry carries its own lifecycle window because a matrix cannot be filtered at
# run time, so the step decides for itself whether it belongs in the requested month.
emit_matrix() {
    local definition=$1

    printf 'matrix:\n  include:\n'
    # The quote is passed in rather than written literally, because the jq program is
    # itself single-quoted for the shell.
    yq -o=json '.' "${definition}" | jq -r --arg q "'" '
        .environments[]
        | (if has("release_suffix") then .release_suffix else (.JULIA_VERSION + "-" + (.OS_VERSION | tostring)) end) as $suffix
        | "    - release_suffix: \($q)\($suffix)\($q)",
          "      release_from: \($q)\(.release_from // "0000-01")\($q)",
          "      release_through: \($q)\(.release_through // "9999-12")\($q)",
          (if .R_VERSION != null then "      R_VERSION: \($q)\(.R_VERSION)\($q)" else empty end),
          (if .JULIA_VERSION != null then "      JULIA_VERSION: \($q)\(.JULIA_VERSION)\($q)" else empty end),
          (if .OS_VERSION != null then "      OS_VERSION: \($q)\(.OS_VERSION)\($q)" else empty end)
    '
}

emit_build_args() {
    local definition=$1

    printf '      build_args_from_env:\n'
    yq -o=json '.' "${definition}" | jq -r '
        [.environments[] | keys[]] | unique
        | map(select(. == "R_VERSION" or . == "JULIA_VERSION" or . == "OS_VERSION"))
        | .[]
        | "        - \(.)"
    '
}

for definition in "${repository_root}"/release/environments/*.yaml; do
    image=$(yq -r '.image' "${definition}")
    platforms=$(yq -r '.platforms' "${definition}")
    merge_dependencies=()

    while IFS= read -r platform; do
        architecture=${platform#linux/}
        workflow="${output_directory}/build-${image}-${architecture}.yaml"
        merge_dependencies+=("build-${image}-${architecture}")

        {
            generated_banner
            cat <<YAML
when:
  event:
    - manual
  branch:
    - main

depends_on:
  - lint

# backend selects a Docker agent, because a local-backend agent execs the image
# field as a command. platform keeps an arm64 build off an amd64 agent, where it
# would fall back to emulation these images cannot survive.
labels:
  backend: docker
  platform: ${platform}

variables:
  RELEASE_MONTH:
    description: Calendar month to build as YYYY-MM. Crow cron cannot supply it, so every release run states it.
    required: true

YAML
            emit_matrix "${definition}"
            cat <<YAML

steps:
  build-image:
    when:
      evaluate: 'RELEASE_MONTH >= release_from && RELEASE_MONTH <= release_through'
    image: ${plugin_image}
    settings:
      mtu: 1350
      platforms: ${platform}
      repo: ${release_registry}/${image}
      tags: \${RELEASE_MONTH}-\${release_suffix}-${architecture}
      dockerfile: ${image}/Containerfile
      provenance: true
      sbom: true
YAML
            emit_build_args "${definition}"
            registry_login
        } >"${workflow}"
    done < <(tr ',' '\n' <<<"${platforms}")

    workflow="${output_directory}/merge-${image}.yaml"
    {
        generated_banner
        printf 'when:\n  event:\n    - manual\n  branch:\n    - main\n\ndepends_on:\n'
        printf '  - %s\n' "${merge_dependencies[@]}"
        cat <<YAML

# Composing an index reads registry metadata only, so it needs no builder.
labels:
  backend: docker

variables:
  RELEASE_MONTH:
    description: Calendar month to compose as YYYY-MM. Crow cron cannot supply it, so every release run states it.
    required: true

YAML
        emit_matrix "${definition}"
        cat <<YAML

steps:
  merge-manifest:
    when:
      evaluate: 'RELEASE_MONTH >= release_from && RELEASE_MONTH <= release_through'
    image: ${plugin_image}
    settings:
      manifest: true
      repo: ${release_registry}/${image}
      tags: \${RELEASE_MONTH}-\${release_suffix}
      manifest_sources:
YAML
        while IFS= read -r platform; do
            # shellcheck disable=SC2016  # ${...} is Crow substitution, resolved at run time
            printf '        - %s/%s:${RELEASE_MONTH}-${release_suffix}-%s\n' \
                "${release_registry}" "${image}" "${platform#linux/}"
        done < <(tr ',' '\n' <<<"${platforms}")
        registry_login
    } >"${workflow}"
done

echo "Rendered release workflows into ${output_directory}"
