#!/usr/bin/env bash

set -euo pipefail

repository_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
config="${repository_root}/r/sysreqs/config.json"
mode=${1:-update}
if [[ ${mode} != update && ${mode} != --check ]]; then
  echo "Usage: $0 [--check]" >&2
  exit 1
fi
revision=$(jq -r '.revision' "${config}")
if [[ ! ${revision} =~ ^[a-f0-9]{40}$ ]]; then
  echo "Pin a full upstream commit in r/sysreqs/config.json" >&2
  exit 1
fi
temporary=$(mktemp -d)
trap 'rm -rf "${temporary}"' EXIT
curl -fsSL "https://codeload.github.com/rstudio/r-system-requirements/tar.gz/${revision}" -o "${temporary}/source.tar.gz"
mkdir "${temporary}/source"
tar -xzf "${temporary}/source.tar.gz" --strip-components=1 -C "${temporary}/source"
for rule in "${temporary}"/source/rules/*.json; do
  jq --arg name "$(basename "${rule}" .json)" '. + {name: $name}' "${rule}"
done | jq -s '.' >"${temporary}/rules.json"

while IFS=$'\t' read -r id family; do
  output="${temporary}/${id}"
  mkdir -p "${output}"
  jq -e --slurpfile config "${config}" --arg id "${id}" \
    '($config[0].platforms[] | select(.id == $id)) as $platform |
    any(.[]; .distribution == $platform.distribution and (.versions | index($platform.version)) != null)' \
    "${temporary}/source/systems.json" >/dev/null
  jq --slurpfile config "${config}" --arg id "${id}" \
    -f "${repository_root}/scripts/render-r-sysreqs.jq" "${temporary}/rules.json" >"${output}/manifest.json"
  {
    printf '#!/bin/sh\n\n# Generated by scripts/update-r-sysreqs.sh from %s.\nset -eu\n\n' "${revision}"
    if [[ ${family} == ubuntu ]]; then
      printf 'export DEBIAN_FRONTEND=noninteractive\n'
    fi
    jq -r '.pre_install[]' "${output}/manifest.json"
    case "${family}" in
      ubuntu) printf 'apt-get update\napt-get install --no-install-recommends -y' ;;
      alma) printf 'dnf install -y --nodocs' ;;
      alpine) printf 'apk add --no-cache' ;;
    esac
    while IFS= read -r package; do
      printf ' \\\n  %s' "${package}"
    done < <(jq -r '.packages[] | @sh' "${output}/manifest.json")
    printf '\n'
    jq -r '.post_install[]' "${output}/manifest.json"
    cat <<'EOF'

# Each bundled R installation needs its own Java configuration.
for r in /opt/R/*/bin/R; do
  "$r" CMD javareconf
done
EOF
  } >"${output}/install.sh"
  if [[ ${mode} == --check ]]; then
    diff -u <(jq -S . "${repository_root}/r/sysreqs/${id}/manifest.json") <(jq -S . "${output}/manifest.json")
    diff -u "${repository_root}/r/sysreqs/${id}/install.sh" "${output}/install.sh"
  fi
done < <(jq -r '.platforms[] | [.id, .family] | @tsv' "${config}")

if [[ ${mode} == update ]]; then
  while IFS= read -r id; do
    mkdir -p "${repository_root}/r/sysreqs/${id}"
    cp "${temporary}/${id}/manifest.json" "${temporary}/${id}/install.sh" "${repository_root}/r/sysreqs/${id}/"
  done < <(jq -r '.platforms[].id' "${config}")
fi
